"""
StatisticalDetectService — Production anomaly detection engine.

Design rationale (per REVIEW_v2_detect_anomaly.md §4b):
  The XGBoost v2 model achieves 0.118 precision on true labels because it was trained
  on synthetic CPU/memory metrics generated by the team to match their own labels.
  The correct approach is mechanism-specific statistical detectors that operate solely
  on CUR cost behaviour — no synthetic sensor data required.

Five detectors, one per AnomalyType:

  sudden_spike   → robust_z > threshold OR cost_ratio_to_7d_avg > 5×
  gradual_drift  → linear slope of rolling 14d cost trend > 0
  idle_resource  → cost > 0 AND usage_density_24h < 0.05 AND cpu < 10%
  runaway_usage  → usage_density_24h ≥ 0.95 AND cost_ratio > 1.5 AND
                   NOT in benign-context (campaign/load-test)
  untagged_spend → cost > $50/day AND (team_missing OR owner_missing)

Confidence calibration:
  Each detector returns a raw score [0, 1]. Scores are clipped to [0.55, 0.99].
  telemetry_delay_event=True penalises confidence by −0.08 (per contract §5.1).

Optional XGBoost overlay:
  If DATA_DIR or MLFLOW_TRACKING_URI is set and a valid model loads, its anomaly
  probability (class=1) is averaged with the statistical score at weight 0.3/0.7
  (XGB / statistical). This avoids over-reliance on the potentially-biased model
  while still using it as a signal.
"""

from __future__ import annotations

import datetime
import logging
import os
import random
import string
import uuid
from typing import Any

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

from app.models.enums import AnomalyType, RemediationStatus, Severity, DataConfidence, DataSourceType
from app.schemas.detect import AlertRouting, AnomalyItem, CURLineItem, DetectRequest, DetectResponse
from app.schemas.status import ActionLogEntry, RemediationStatusResponse
from app.services.base import DetectService


_status_store: dict[str, RemediationStatusResponse] = {}
_anomalies_registry: dict[str, dict] = {}


ROBUST_Z_THRESHOLD = 2.5
COST_RATIO_THRESHOLD = 5.0
DRIFT_SLOPE_THRESHOLD = 0.0
IDLE_USAGE_DENSITY = 0.05
IDLE_CPU_THRESHOLD = 10.0
RUNAWAY_USAGE_DENSITY = 0.95
RUNAWAY_COST_RATIO = 1.5
UNTAGGED_COST_FLOOR = 50.0
PEER_RATIO_THRESHOLD = 3.0
YOUNG_RESOURCE_MAX_AGE = 14
YOUNG_ABSOLUTE_COST_FLOOR = 150.0



def _make_anomaly_id(used: set[str]) -> str:
    today = datetime.date.today()
    for _ in range(100):
        letter = random.choice(string.ascii_uppercase)
        aid = f"ANM-{today.year}-{today.month:02d}{today.day:02d}{letter}"
        if aid not in used:
            return aid
    return f"ANM-{today.year}-{today.month:02d}{today.day:02d}Z"



def _severity(anomaly_type: AnomalyType, cost: float, ratio: float) -> Severity:
    if anomaly_type in (AnomalyType.runaway_usage, AnomalyType.sudden_spike):
        return Severity.HIGH
    if cost > 500 or ratio > 10:
        return Severity.HIGH
    if anomaly_type == AnomalyType.gradual_drift:
        return Severity.LOW
    return Severity.MEDIUM




def _detect_sudden_spike(
    cost: float,
    rolling_avg: float,
    rolling_std: float,
    rolling_median: float,
    rolling_mad: float,
) -> tuple[bool, float, str]:
    """
    Sudden spike: cost far above recent history in a single day.
    Uses robust_z (MAD-based) to avoid sensitivity to prior outliers.
    """
    robust_z = 0.6745 * (cost - rolling_median) / (rolling_mad + 1e-6) if rolling_mad > 0 else 0.0
    cost_ratio = cost / (rolling_avg + 1e-6)

    if robust_z > ROBUST_Z_THRESHOLD or cost_ratio > COST_RATIO_THRESHOLD:
        score = min(0.99, 0.60 + 0.08 * min(robust_z / ROBUST_Z_THRESHOLD, 5.0))
        return True, round(score, 2), "robust_z"
    return False, 0.0, ""


def _detect_gradual_drift(
    slope_14d: float,
    cost_pct_change_28d: float,
) -> tuple[bool, float, str]:
    """
    Gradual drift: sustained upward cost trend over 14–28 days.
    Positive slope_14d combined with 28-day growth > 10%.
    """
    if slope_14d > DRIFT_SLOPE_THRESHOLD and cost_pct_change_28d > 0.10:
        score = min(0.99, 0.58 + 0.25 * min(cost_pct_change_28d, 1.0))
        return True, round(score, 2), "slope_14d"
    return False, 0.0, ""


def _detect_idle_resource(
    cost: float,
    usage_amount: float,
    usage_density: float,
    cpu_mean: float | None,
    product_code: str,
) -> tuple[bool, float, str]:
    """
    Idle resource: provisioned and billed with near-zero utilisation.
    Only fires when cost > $0 (resource is actually being charged).
    Lambda/S3 excluded — their usage density patterns differ.
    """
    excluded_services = {"AWSLambda", "AmazonS3", "AWSDataTransfer", "AWSELB"}
    if product_code in excluded_services:
        return False, 0.0, ""
    if cost < 1.0:
        return False, 0.0, ""


    density_idle = usage_density <= IDLE_USAGE_DENSITY


    cpu_idle = (cpu_mean is not None and cpu_mean < IDLE_CPU_THRESHOLD)

    if density_idle or cpu_idle:
        score = 0.72 if (density_idle and cpu_idle) else 0.60
        driver = "usage_density_24h" if density_idle else "cpu_mean"
        return True, round(score, 2), driver
    return False, 0.0, ""


def _detect_runaway_usage(
    cost: float,
    cost_ratio: float,
    usage_density: float,
    cpu_mean: float | None,
    business_context: dict,
) -> tuple[bool, float, str]:
    """
    Runaway usage: resource running at near-100% capacity continuously
    without a legitimate business reason (campaign, load test, migration).
    """

    if (
        business_context.get("campaign_flag")
        or business_context.get("load_test_flag")
        or business_context.get("migration_flag")
    ):
        return False, 0.0, ""

    density_runaway = usage_density >= RUNAWAY_USAGE_DENSITY
    cpu_runaway = (cpu_mean is not None and cpu_mean > 80.0)
    ratio_elevated = cost_ratio > RUNAWAY_COST_RATIO

    if (density_runaway or cpu_runaway) and ratio_elevated:
        score = min(0.99, 0.70 + 0.10 * min(cost_ratio / RUNAWAY_COST_RATIO, 3.0))
        driver = "usage_density_24h" if density_runaway else "cpu_mean"
        return True, round(score, 2), driver
    return False, 0.0, ""


def _detect_untagged_spend(
    cost: float,
    team_missing: bool,
    owner_missing: bool,
    product_code: str,
    business_context: dict | None = None,
) -> tuple[bool, float, str]:
    """
    Untagged spend: significant daily cost with no team or owner tag.
    Cannot route alert to a responsible squad.

    Finance-approved benign context (ticketed migration / campaign / load-test)
    suppresses the alert: a one-off egress burst that Finance already signed off on
    (the 'B2' trap) must not be raised just because the transient resource is
    untagged.
    """
    business_context = business_context or {}
    if (
        business_context.get("campaign_flag")
        or business_context.get("load_test_flag")
        or business_context.get("migration_flag")
    ):
        return False, 0.0, ""
    if cost >= UNTAGGED_COST_FLOOR and (team_missing or owner_missing):
        score = 0.80 if (team_missing and owner_missing) else 0.65
        return True, round(score, 2), "resource_tags_user_team"
    return False, 0.0, ""


def _detect_young_resource_spike(
    cost: float,
    age_days: int,
    peer_ratio: float,
    business_context: dict,
) -> tuple[bool, float, str]:
    """
    Young-resource spike: catch expensive resources that appear with NO prior
    baseline (the classic 'A6' miss — a debug log-group spun up only during the
    incident, so every observed day is already inside the anomaly).

    Rolling robust_z / cost_ratio detectors are blind here because there is no
    pre-incident history to deviate from. We fall back to two baseline-free signals:
      * peer_ratio — cost far above the median of the same account+service+day (relative)
      * absolute   — cost over an absolute daily floor (magnitude)

    Benign, Finance-approved context (migration / campaign / load-test) suppresses
    it, so ticketed one-off bursts (the 'B2' egress trap) are not flagged.
    """
    if age_days >= YOUNG_RESOURCE_MAX_AGE:
        return False, 0.0, ""
    if (
        business_context.get("campaign_flag")
        or business_context.get("load_test_flag")
        or business_context.get("migration_flag")
    ):
        return False, 0.0, ""

    peer_hit = peer_ratio > PEER_RATIO_THRESHOLD
    abs_hit = cost > YOUNG_ABSOLUTE_COST_FLOOR
    if peer_hit or abs_hit:
        score = 0.70 if (peer_hit and abs_hit) else 0.62
        driver = "peer_ratio" if peer_hit else "absolute_cost_spike"
        return True, round(score, 2), driver
    return False, 0.0, ""




def _compute_rolling_stats(
    cost: float,
    history: list[float],
) -> dict[str, float]:
    """
    Compute rolling statistics from historical cost values (most recent last).
    History should be the resource's prior costs (shift-1, not including current).
    """
    if not history:
        return {
            "rolling_avg": cost, "rolling_std": 0.0,
            "rolling_median": cost, "rolling_mad": 0.0,
            "slope_14d": 0.0, "cost_pct_change_28d": 0.0,
        }

    window_7 = history[-7:] if len(history) >= 7 else history
    window_14 = history[-14:] if len(history) >= 14 else history
    window_28 = history[-28:] if len(history) >= 28 else history

    rolling_avg = float(np.mean(window_7))
    rolling_std = float(np.std(window_7)) if len(window_7) > 1 else 0.0
    rolling_median = float(np.median(window_14))
    rolling_mad = float(np.median(np.abs(np.array(window_14) - np.median(window_14))))


    slope_14d = 0.0
    if len(window_14) >= 4:
        from scipy.stats import linregress
        x = np.arange(len(window_14))
        try:
            slope_14d = float(linregress(x, window_14).slope)
        except Exception:
            slope_14d = 0.0


    cost_pct_change_28d = 0.0
    if window_28:
        lag_28 = window_28[0]
        cost_pct_change_28d = (cost - lag_28) / (lag_28 + 1e-6)

    return {
        "rolling_avg": rolling_avg,
        "rolling_std": rolling_std,
        "rolling_median": rolling_median,
        "rolling_mad": rolling_mad,
        "slope_14d": slope_14d,
        "cost_pct_change_28d": cost_pct_change_28d,
    }




class _SklearnOverlay:
    """Adapter so a joblib-saved sklearn model satisfies the overlay contract.

    Trained by ai-engine/scripts/train_overlay.py with FEATURE_v2 column parity.
    Selects/reorders the model's expected feature columns from the incoming X so
    predict_proba(X)[:, 1] = anomaly probability, just like the XGBoost path.
    """

    def __init__(self, model: Any, features: list[str]) -> None:
        self._model = model
        self._features = features

    def predict_proba(self, X):
        cols = [f for f in self._features if f in X.columns]
        return self._model.predict_proba(X[cols])


def _try_load_sklearn_overlay() -> Any | None:
    """Load the sklearn overlay if AI_OVERLAY_MODEL points to a joblib bundle.

    Activates the hybrid in environments without xgboost installed (the common
    case here). Returns None silently if unset/missing/unloadable.
    """
    path = os.getenv("AI_OVERLAY_MODEL", "")
    if not path or not os.path.exists(path):
        return None
    try:
        import joblib
        bundle = joblib.load(path)
        overlay = _SklearnOverlay(bundle["model"], bundle["features"])
        logger.info("Sklearn overlay loaded from %s (trained_at=%s)",
                    path, bundle.get("trained_at", "?"))
        return overlay
    except Exception as e:
        logger.debug("Sklearn overlay load failed: %s", e)
        return None


def _try_load_xgb_model() -> Any | None:
    """Load an ML overlay model if available. Returns None silently if not found.

    Priority: sklearn joblib (AI_OVERLAY_MODEL) → MLflow XGBoost → local model.ubj.
    """
    sk = _try_load_sklearn_overlay()
    if sk is not None:
        return sk

    mlflow_uri = os.getenv("MLFLOW_TRACKING_URI")
    if mlflow_uri:
        try:
            import mlflow
            import mlflow.xgboost
            mlflow.set_tracking_uri(mlflow_uri)
            client = mlflow.MlflowClient()
            for name in ["AWS_Cost_Anomaly_Detection_v2_Features",
                         "AWS_Cost_Anomaly_Detection_LeakFree"]:
                try:
                    versions = client.get_latest_versions(name, stages=["Production", "Staging", "None"])
                    if versions:
                        model = mlflow.xgboost.load_model(f"models:/{name}/{versions[0].version}")
                        logger.info("XGBoost overlay loaded from MLflow: %s", name)
                        return model
                except Exception:
                    continue
        except Exception as e:
            logger.debug("MLflow overlay unavailable: %s", e)

    data_dir = os.getenv("DATA_DIR", "")
    if data_dir:
        import glob
        files = sorted(glob.glob(os.path.join(data_dir, "mlruns", "**", "model.ubj"), recursive=True))
        if files:
            try:
                from xgboost import XGBClassifier
                m = XGBClassifier()
                m.load_model(files[-1])
                logger.info("XGBoost overlay loaded from: %s", files[-1])
                return m
            except Exception as e:
                logger.debug("Local XGBoost overlay load failed: %s", e)
    return None




class StatisticalDetectService(DetectService):
    """
    Production anomaly detection service using mechanism-specific statistical detectors.

    Does NOT depend on:
      - Synthetic CPU/memory metrics (REVIEW §2.1 blocking issue)
      - Trained model file (works immediately on deployment)

    Optionally blends XGBoost probability (weight 0.3) if a model is available,
    but statistical score (weight 0.7) always dominates.
    """

    XGB_WEIGHT = 0.30
    STAT_WEIGHT = 0.70

    def __init__(self) -> None:
        self._xgb_model = _try_load_xgb_model()
        self._xgb_available = self._xgb_model is not None
        if self._xgb_available:
            logger.info("XGBoost overlay active (weight=%.0f%%)", self.XGB_WEIGHT * 100)
        else:
            logger.info("Statistical-only mode (no XGBoost model found)")



    def detect(self, request: DetectRequest, correlation_id: str) -> DetectResponse:

        data_confidence = DataConfidence.LOW if request.telemetry_delay_event else DataConfidence.HIGH
        cur_items = request.aws_cur_line_items or []


        if not cur_items and request.data_source_type == DataSourceType.S3_POINTER and request.s3_bucket_uri:
            from app.services.ml.cur_source import load_cur_pointer

            for row in load_cur_pointer(request.s3_bucket_uri):
                try:
                    cur_items.append(CURLineItem(**row))
                except Exception as e:
                    logger.debug("Skipping malformed CUR row from pointer: %s", e)

        if not cur_items:
            return DetectResponse(
                success=True,
                correlation_id=correlation_id,
                anomalies_detected=False,
                data_confidence=data_confidence,
                anomalies_list=[],
            )


        metrics_lut: dict[str, dict] = {}
        for m in (request.resource_utilization_metrics or []):
            hourly = getattr(m, "hourly_cpu_percent", None) or []
            cpu_arr = np.array(hourly) if hourly else np.array([getattr(m, "cpu_percent", 50.0)])
            metrics_lut[m.resource_id] = {
                "cpu_mean": float(cpu_arr.mean()),
                "usage_density": float(getattr(m, "usage_density_24h",
                    len([v for v in hourly if v > 5]) / 24 if hourly else 0.5)),
            }


        business_ctx: dict = {}
        if hasattr(request, "business_context") and request.business_context:
            bc = request.business_context
            business_ctx = {
                "campaign_flag": getattr(bc, "campaign_flag", False),
                "load_test_flag": getattr(bc, "load_test_flag", False),
                "migration_flag": getattr(bc, "migration_flag", False),
            }

        confidence_penalty = 0.08 if request.telemetry_delay_event else 0.0



        ce_ratio_by_service: dict[str, float] = {}
        for ce in (request.aws_cost_explorer_daily or []):
            svc_code = getattr(ce, "service_code", None) or ce.get("service_code", "")
            ratio_val = getattr(ce, "cost_ratio_to_7d_avg", None) or ce.get("cost_ratio_to_7d_avg", 1.0)
            if svc_code:
                ce_ratio_by_service[svc_code] = float(ratio_val)



        history_by_resource: dict[str, list[float]] = {}
        for item in sorted(cur_items, key=lambda x: x.line_item_usage_start_date):
            rid = item.line_item_resource_id
            history_by_resource.setdefault(rid, [])


        peer_groups: dict[tuple, list[float]] = {}
        for item in cur_items:
            key = (item.line_item_usage_account_id, item.line_item_product_code,
                   item.line_item_usage_start_date[:10])
            peer_groups.setdefault(key, []).append(float(item.line_item_unblended_cost))
        peer_median: dict[tuple, float] = {k: float(np.median(v)) for k, v in peer_groups.items()}


        xgb_proba: np.ndarray | None = None
        if self._xgb_available:
            try:
                from app.services.ml.feature_builder import build_feature_dataframe
                X, _ = build_feature_dataframe(
                    cur_items,
                    metrics=request.resource_utilization_metrics,
                )
                proba_all = self._xgb_model.predict_proba(X)
                xgb_proba = proba_all[:, 1]
            except Exception as e:
                logger.warning("XGBoost scoring failed, using statistical only: %s", e)
                xgb_proba = None

        anomalies: list[AnomalyItem] = []
        used_ids: set[str] = set()

        for idx, item in enumerate(cur_items):
            rid = item.line_item_resource_id
            cost = float(item.line_item_unblended_cost)
            usage_amount = float(item.line_item_usage_amount)
            product_code = item.line_item_product_code


            usage_density = float(getattr(item, "usage_density_24h", 0.5))


            team_missing = item.resource_tags_user_team is None
            owner_missing = item.resource_tags_user_owner is None


            met = metrics_lut.get(rid, {})
            cpu_mean: float | None = met.get("cpu_mean")


            history = history_by_resource.get(rid, [])
            stats = _compute_rolling_stats(cost, history)
            history_by_resource[rid] = history + [cost]

            peer_key = (item.line_item_usage_account_id, product_code,
                        item.line_item_usage_start_date[:10])
            peer_med = peer_median.get(peer_key, cost)
            peer_ratio = cost / (peer_med + 1e-6)


            detected = False
            stat_score = 0.0
            anomaly_type = AnomalyType.sudden_spike
            driver_feature = "cost_ratio_to_7d_avg"





            ce_ratio = ce_ratio_by_service.get(product_code, 1.0)
            if not history and ce_ratio > COST_RATIO_THRESHOLD and cost > UNTAGGED_COST_FLOOR:
                implied_avg = cost / ce_ratio
                stats["rolling_avg"] = implied_avg
                stats["rolling_median"] = implied_avg
                stats["rolling_mad"] = implied_avg * 0.1

            cost_ratio = cost / (stats["rolling_avg"] + 1e-6)


            flagged, score, driver = _detect_sudden_spike(
                cost, stats["rolling_avg"], stats["rolling_std"],
                stats["rolling_median"], stats["rolling_mad"],
            )
            if flagged and score > stat_score:
                detected, stat_score, anomaly_type, driver_feature = True, score, AnomalyType.sudden_spike, driver


            flagged, score, driver = _detect_untagged_spend(
                cost, team_missing, owner_missing, product_code, business_ctx
            )
            if flagged and score > stat_score:
                detected, stat_score, anomaly_type, driver_feature = True, score, AnomalyType.untagged_spend, driver


            flagged, score, driver = _detect_runaway_usage(
                cost, cost_ratio, usage_density, cpu_mean, business_ctx
            )
            if flagged and score > stat_score:
                detected, stat_score, anomaly_type, driver_feature = True, score, AnomalyType.runaway_usage, driver


            flagged, score, driver = _detect_idle_resource(cost, usage_amount, usage_density, cpu_mean, product_code)
            if flagged and score > stat_score:
                detected, stat_score, anomaly_type, driver_feature = True, score, AnomalyType.idle_resource, driver


            flagged, score, driver = _detect_gradual_drift(stats["slope_14d"], stats["cost_pct_change_28d"])
            if flagged and score > stat_score:
                detected, stat_score, anomaly_type, driver_feature = True, score, AnomalyType.gradual_drift, driver



            flagged, score, driver = _detect_young_resource_spike(
                cost, len(history), peer_ratio, business_ctx
            )
            if flagged and score > stat_score:
                detected, stat_score, anomaly_type, driver_feature = True, score, AnomalyType.sudden_spike, driver


            if not detected and peer_ratio > PEER_RATIO_THRESHOLD and cost > UNTAGGED_COST_FLOOR:
                detected = True
                stat_score = 0.60
                anomaly_type = AnomalyType.sudden_spike
                driver_feature = "peer_ratio"

            if not detected:
                continue


            if xgb_proba is not None and idx < len(xgb_proba):
                blended = self.STAT_WEIGHT * stat_score + self.XGB_WEIGHT * float(xgb_proba[idx])
                final_score = round(min(0.99, max(0.50, blended - confidence_penalty)), 2)
                model_tag = f"statistical+ml-overlay:{driver_feature}"
            else:
                final_score = round(min(0.99, max(0.50, stat_score - confidence_penalty)), 2)
                model_tag = f"statistical:{driver_feature}"

            env = getattr(item, "resource_tags_user_environment", "dev")
            severity = _severity(anomaly_type, cost, cost_ratio)
            finance_alert = cost > 200 or cost_ratio > 5.0

            anomaly_id = _make_anomaly_id(used_ids)
            used_ids.add(anomaly_id)

            anomaly = AnomalyItem(
                anomaly_id=anomaly_id,
                anomaly_type=anomaly_type,
                severity=severity,
                confidence_score=final_score,
                resource_id=rid,
                environment=env,
                responsible_team=item.resource_tags_user_team,
                unblended_cost_24h_usd=round(cost, 2),
                cost_ratio_to_7d_avg=round(cost_ratio, 2),
                ai_model_used=model_tag,
                alert_routing=AlertRouting(finance=finance_alert, engineering=True),
            )
            anomalies.append(anomaly)


            _anomalies_registry[anomaly_id] = {
                "resource_id": rid,
                "environment": env,
                "confidence_score": final_score,
                "line_item_product_code": product_code,
                "line_item_unblended_cost": cost,
                "cost_ratio_to_7d_avg": cost_ratio,
                "usage_density_24h": usage_density,
                "cpu_mean": cpu_mean,
                "resource_tags_user_owner": item.resource_tags_user_owner,
                "resource_tags_user_team": item.resource_tags_user_team,
                "absolute_cost_spike": stats.get("absolute_cost_spike", 0.0) if "stats" in locals() else 0.0,
                "database_connections": met.get("database_connections", 0.0) if met else 0.0,
            }

            _status_store[anomaly_id] = RemediationStatusResponse(
                audit_id=str(uuid.uuid4()),
                anomaly_id=anomaly_id,
                status=RemediationStatus.PENDING_APPROVAL,
                containment_locked=False,
                error_budget_remaining_pct=100.0,
                actions_log=[],
            )

        return DetectResponse(
            success=True,
            correlation_id=correlation_id,
            anomalies_detected=len(anomalies) > 0,
            data_confidence=data_confidence,
            anomalies_list=anomalies,
        )

    def get_status(self, anomaly_id: str) -> RemediationStatusResponse | None:
        return _status_store.get(anomaly_id)

    @staticmethod
    def get_anomaly_raw(anomaly_id: str) -> dict | None:
        return _anomalies_registry.get(anomaly_id)

    @staticmethod
    def update_status(
        anomaly_id: str,
        new_status: RemediationStatus,
        log_entry: ActionLogEntry,
        containment_locked: bool | None = None,
        error_budget_remaining_pct: float | None = None,
    ) -> None:
        record = _status_store.get(anomaly_id)
        if record:
            record.status = new_status
            record.actions_log.append(log_entry)
            if containment_locked is not None:
                record.containment_locked = containment_locked
            if error_budget_remaining_pct is not None:
                record.error_budget_remaining_pct = error_budget_remaining_pct
